[window]
padding.x = 5
padding.y = 5

[font]
normal.family = "FiraCode Nerd Font Mono"
bold.family = "FiraCode Nerd Font Mono"
italic.family = "FiraCode Nerd Font Mono"
bold_italic.family = "FiraCode Nerd Font Mono"
size = 10.0

[colors]
primary.background = "#020932"
primary.foreground = "#d7f3f5"

[cursor]
style.shape = "Underline"

[terminal]
shell = "/bin/zsh"